In [1]:
import torch
w = torch.empty(10,10)

In [2]:
w

tensor([[ 0.0000e+00, -2.0000e+00,  0.0000e+00, -2.0000e+00,  3.7835e-44,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 2.3752e-34,  1.4013e-45,  1.4013e-45,  2.2369e+08,  0.0000e+00,
          0.0000e+00,  0.0000e+00, -2.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  9.2196e-41,  0.0000e+00,  2.2369e+08],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  2.9511e-34,  1.4013e-45,  1.4013e-45,  1.4013e-45],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.4013e-44,  9.2196e-41,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  6.4954e-34,  1.4013e-45,  1.4013e-45,
         -2.0000e+00,  0.0000e+0

In [14]:
w.shape
torch.randn(w.shape) < 1
#w[torch.randn(w.shape)]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 0, 1, 1, 1, 0, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 0, 1, 0],
        [1, 1, 0, 1, 1, 1, 1, 1, 0, 1],
        [1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 0, 1, 1, 1, 1, 1, 1, 0, 1],
        [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
        [1, 0, 0, 1, 1, 0, 1, 1, 1, 0],
        [0, 1, 0, 1, 1, 1, 1, 1, 1, 1]], dtype=torch.uint8)

In [24]:
x = []
for i in range(10):
    x.append(torch.tensor([i, i+1, i+2]))

In [25]:
x

[tensor([0, 1, 2]),
 tensor([1, 2, 3]),
 tensor([2, 3, 4]),
 tensor([3, 4, 5]),
 tensor([4, 5, 6]),
 tensor([5, 6, 7]),
 tensor([6, 7, 8]),
 tensor([7, 8, 9]),
 tensor([ 8,  9, 10]),
 tensor([ 9, 10, 11])]

In [17]:
x[1:]

[tensor(1),
 tensor(2),
 tensor(3),
 tensor(4),
 tensor(5),
 tensor(6),
 tensor(7),
 tensor(8),
 tensor(9)]

In [18]:
x[:]

[tensor(0),
 tensor(1),
 tensor(2),
 tensor(3),
 tensor(4),
 tensor(5),
 tensor(6),
 tensor(7),
 tensor(8),
 tensor(9)]

In [35]:
import numpy as np
y = np.vstack(x)
y.T[:]
#y.T[:,0:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])